Specify dataset version used by funeTuning workload (#5736)
To workaround this issue when loading dataset when running qloar fineTuning nf4 case:

RuntimeError: Dataset scripts are no longer supported, but found viggo.py