fix test_sycl_queue.py (#5391)
Fix the ERROR test_sycl_queue.py - TypeError: ExtensionVersioner.bump_version_if_changed() missing 1 required positional argument: 'with_sycl'. PyTorch 2.7 changed the API bump_version_if_changed in torch/utils/_cpp_extension_versioner.py in pytorch/pytorch#132945.