Specify dataset version used by funeTuning workload (#5736)(#5738)
To workaround this issue when loading dataset when running qloar fineTuning nf4 case:
RuntimeError: Dataset scripts are no longer supported, but found viggo.py

* set use_cache=False in LLama2 fineTuning case

* fix datasets version to v3.6.0 in QLora fineTuning case